import type { Z1Board } from "../types/Z1Board";

export const boardList: Z1Board[] = [
  { name: "L1のトライフォースを取得する", category: "triforce" },
  { name: "L2のトライフォースを取得する", category: "triforce" },
  { name: "L3のトライフォースを取得する", category: "triforce" },
  { name: "L4のトライフォースを取得する", category: "triforce" },
  { name: "L5のトライフォースを取得する", category: "triforce" },
  { name: "L6のトライフォースを取得する", category: "triforce" },
  { name: "L7のトライフォースを取得する", category: "triforce" },
  { name: "L8のトライフォースを取得する", category: "triforce" },

  { name: "ボムを2回購入する", category: "shopping", count: 2 },
  { name: "ブルーリングを購入する", category: "shopping" },
  { name: "青いろうそくを購入する", category: "shopping" },
  { name: "マジカルシールドを購入する", category: "shopping" },
  { name: "クスリを購入する", category: "shopping" },
  { name: "キーを購入する", category: "shopping" },
  { name: "エサを購入する", category: "shopping" },
  { name: "ヒントを買う", category: "shopping" },

  { name: "コンパスを4個取得する", category: "correcting", count: 4 },
  { name: "地図を4枚取得する", category: "correcting", count: 4 },
  { name: "ボムアップグレードを入手する", category: "correcting" },
  { name: "マジカルキーを入手する", category: "correcting" },
  { name: "赤いろうそくを入手する", category: "correcting" },
  { name: "時計を3回取得する", category: "correcting", count: 3 },
  { name: "キーを10個集める", category: "correcting", count: 10 },

  { name: "赤オクタロックを20体倒す", category: "monster", count: 20 },
  { name: "赤ライネルを5体倒す", category: "monster", count: 5 },
  { name: "ピーハットを5体倒す", category: "monster", count: 5 },
  { name: "ゾーラを3体倒す", category: "monster", count: 3 },
  { name: "ギーニを1画面に12体出現させる", category: "monster" },
  { name: "アモスを倒さずに1画面で10体触れて動かす", category: "monster" },
  { name: "ウォールマスターに捕まる", category: "monster" },
  { name: "モリブリンの槍の攻撃を10回防ぐ", category: "monster", count: 10 },
  { name: "岩に5回あたる", category: "monster" },

  {
    name: "ドアの修理代請求おじいさんに2回会う",
    category: "sightseeing",
    count: 2,
  },
  { name: "ギャンブルでお金を増やす", category: "sightseeing" },
  { name: "笛でワープする", category: "sightseeing" },
  { name: "L9に行く", category: "sightseeing" },

  { name: "「オカネガナクナレバ　ヤ　ハ　ツカエナイ」", category: "hint" },
  { name: "「ドドンゴ　ハ　ケムリ　ヲ　キラウ」", category: "hint" },
  {
    name: "「タキノウエノジイサン二　ケンヲ　モラッタカイ」",
    category: "hint",
  },
  { name: "「タキ　ノ　ナカ　二　ハイレ」", category: "hint" },
  { name: "「デグドガニハ　キライ　ナ　オトガ　アル」", category: "hint" },
  { name: "「オトニヨワイ　イキモノ　ガイル」", category: "hint" },
  { name: "「ゴーマ　ノ　メヲネラエ」", category: "hint" },
  { name: "「ヨウセイノスマヌイズミ　ニハ　ヒミツガアル」", category: "hint" },
  { name: "「メガネイワ　ハ　シヘノ　イリグチ」", category: "hint" },
  { name: "「デスマウンテンデ　ヤヲ　サガセ」", category: "hint" },
  { name: "「ライオンノカギヲサガセ」", category: "hint" },
];
